services:
  web:
    image: nginx:latest
    restart: always
    ports:
      - '8080:80'
    volumes:
      - ./web/data:/var/www/html
      - ./web/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    image: php:8-fpm
    restart: always
    volumes:
      - ./web/data:/var/www/html